basePath: /
definitions:
  handler.AmountRequest:
    properties:
      amount:
        type: number
    type: object
  handler.BalanceResponse:
    properties:
      balance:
        type: number
    type: object
  handler.CreateAccountResponse:
    properties:
      id:
        type: string
    type: object
  handler.ErrorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
  title: Swagger API
  version: "1.0"
paths:
  /accounts:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.CreateAccountResponse'
      summary: create account
      tags:
      - accounts
  /accounts/{id}/balance:
    get:
      consumes:
      - application/json
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.BalanceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Get balance
      tags:
      - accounts
  /accounts/{id}/deposit:
    post:
      consumes:
      - application/json
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      - description: Amount
        in: body
        name: amount
        required: true
        schema:
          $ref: '#/definitions/handler.AmountRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Deposit
      tags:
      - accounts
  /accounts/{id}/withdraw:
    post:
      consumes:
      - application/json
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      - description: Amount
        in: body
        name: amount
        required: true
        schema:
          $ref: '#/definitions/handler.AmountRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Withdraw
      tags:
      - accounts
swagger: "2.0"
